# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  studytime
subtitle: 分享技术，品味人生
name: studytime
email: b_aihe@163.com
description: 本站是白贺的技术分享博客。内容涵盖生活故事、PHP后端技术、Java后端技术、大数据、大数据生态、bigData、Spring Boot、微服务架构、高可用架构等相关的研究与知识分享。
keywords: studytime,白贺,Bai He,Big Data, bigdata,Java,Spark,Sqoop,Hadoop,Kafka,Flume、Hive、Hbase、Spring,Spring Boot,SJvm,生活故事,架构,大数据,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客
encoding: "utf-8"
favicon: favicon.png
static-url: https://static.studytime.xin/studytime-Blog

repository: MyStudytime/studytime-blog
github_url: https://github.com/MyStudytime
url: https://www.studytime.xin

sfblog_url: https://segmentfault.com/u/baihe
base_url: https://www.studytime.xin
baseurl: ''
enforce_ssl: https://www.studytime.xin
static-url-version: 20190721

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"


source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  - href: /bigdata.html
    label: bigdata
  -
    href: /PHP.html
    label: PHP

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  -
    href: /Tool.html
    name: 工具

  - href: /mysql.html
    name: mysql

  - href: /blog.html
    name: blog

  - href: /bigdata.html
    name: 大数据

# selected articles
classes:
  - href: /bigdata.html
    name: 大数据
    describe: 大数据浪潮
  -
    href: /Tool.html
    name: 工具
    describe: 工欲善其事，必先利其器
  - href: /mysql.html
    name: mysql
    describe: 数据库


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
google :
  tracking_id : 'UA-131499684-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
gitalk:
  owner: MyStudytime
  repo:  blog-comments
  clientID: f2951c434919f3ebb0da
  clientSecret: 3846a22cae7d971aa40ae159b53c3152f9ff6cd2
